spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: bmicro-we
          uri: http://micro-web
          predicates:
          - Path= /micro-web/**

server:
  port: 6666


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8763/eureka/

