spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: swell
          uri: http://127.0.0.1:20000
          predicates:
            - Path=/swell/**
        - id: wallet
          uri: http://127.0.0.1:9222
          predicates:
            - Path=/wallet/**

server:
  port: 6666

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8763/eureka/

