spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: micro-web
          uri: lb://micro-web
          predicates:
            - Path=/micro-web/**
        - id: micro-order
          uri: lb://micro-order
          predicates:
            - Path=/micro-order/**

server:
  port: 6666


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8763/eureka/

