spring:
  application:
    name: spring-cloud-zuul
server:
  port: 5555

# 不配置路由规则默认是服务名。如：http://127.0.0.1:5555/micro-web/user/queryUser
zuul:
  ignored-services: '*' # 关闭默认路由规则, 不想暴露的接口
  routes:
    api-a:
      path: /swell/**
      serviceId: http://127.0.0.1:20000
    api-b:
      path: /micro-order/**
      serviceId: micro-order
    api-b:
      path: /micro-web/**
      serviceId: micro-web
#  ignored-patterns: ['/micro-a/**','/micro-b/**'] # 忽略某些路径

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin@localhost:8763/eureka/

