spring:
  application:
    name: spring-cloud-zuul
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: MICRO-WEB
    api-b:
      path: /api-b/**
      serviceId: MICRO-ORDER
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8763/eureka/
